app:
    image: ehazlett/docker-demo:latest
    environment:
        INTERLOCK_DATA: '{"hostname":"hello","domain":"docker"}'
    ports:
        - "8080"

db:
    image: redis
    ports:
        - "6379"
